### ISSUE TITLE
Update http://toolkit.globus.org/ftppub/gt6/installers/src/ with newer source tar ball

### ISSUE THREAD

**Issue by davidcarver** [globus/globus-toolkit#101]
Update http://toolkit.globus.org/ftppub/gt6/installers/src/  with newer source tar ball
The last source tar ball is dated  4-Nov-2016.
The webpage http://toolkit.globus.org/toolkit/advisories.html is showing many new patches.

Thanks,
David Carver

**Comment by bester** [comment]
Newer installers are now available

**Comment by davidcarver** [comment]
Thanks Joe!
