### ISSUE TITLE
package checksums do not match in installation instructions

### ISSUE THREAD

**Issue by tpdownes** [globus/globus-toolkit#105]
The [packages that configure the repositories on Debian/Ubuntu](http://toolkit.globus.org/toolkit/downloads/6.0/) do not have accurate checksums posted. It appears to be that you are either linking to an outdated checksum or you're not updating the ones for "latest" because the [checksums for 6.0.12](https://downloads.globus.org/toolkit/gt6/stable/installers/repo/deb/) validate.

**Comment by bester** [comment]
Thanks, my update script wasn't recomputing checksums when making the "latest" links.
