### ISSUE TITLE
globus-toolkit binary install problems

### ISSUE THREAD

**Issue by surhudm** [globus/globus-toolkit#111]
I was trying out the globus-toolkit binary installer to install gridftp-lite (Redhat enterprise linux 6.0). I do not have access to root, so I basically untarred the binary from here:

https://downloads.globus.org/toolkit/gt6/stable/installers/linux/globus_toolkit-latest-x86_64-unknown-linux-gnu.tar.gz

Then ran sbin/gridftp-server-enable-sshftp -nonroot

This created the $HOME/.globus/sshftp file as desired. On the client side I then tried to copy a file using sshftp://. The ssh server authenticates correctly. But then the gridftp server has no response.

I owned another machine (fedora core 26 workstation edition) where I could get gridftp-lite running and working using the rpms available on the website (I had root access this time), but when I try installing using the binaries above on this server as well, I face the same issue of getting no further response.

While debugging intuitively I started looking at the sshftp file. I noticed two things:

1) The user-env.sh file referenced in sshftp had been moved from etc to the share directory. 
2) The globus_location was also set incorrectly to begin at the root directory.

Fixing both these issues did not fix the problem either. Any help would be appreciated.

**Comment by bester** [comment]
1) This is a bug in the script from the installer. I've committed a fix, but a new installer is not yet available. This checks in etc share and share/globus: https://github.com/globus/globus-toolkit/commit/cfddbf779423d24d7fc03fb29644dd5c0bed09bb#diff-5c851603ca29699120086d0da0d65a2b
2) Prior to running gridftp-server-enable-sshftp, you need to set the GLOBUS_LOCATION environment variable. This will change the path in the generated script. You also need to set this in the environment when you run globus-url-copy from the installer.
