### ISSUE TITLE
globus_module_active is not thread safe

### ISSUE THREAD

**Issue by paulmillar** [globus/globus-toolkit#47]
Calls to `globus_module_active` are not safe if done with multiple threads.

Attached is a minimal test-case to demonstrate the problem.  The test should be run on a multi-core machine.

[testcase.c](https://github.com/globus/globus-toolkit/files/270168/testcase.c.txt)

There is a work-around: the application can add protection against concurrent modification by using a mutex.  The testcase code demonstrates this workaround.

The problem was detected using Debian jessie:

```
paul@celebrimbor:~/globus-test-case$ dpkg-query -W *globus*
globus-common-dbg
globus-common-progs
globus-core
globus-gass-copy-progs  9.12-3
globus-gssapi-error-dbg
globus-gssapi-gsi-dbg
globus-rls-client-progs
globus-rls-server
jglobus
libglobus-callout-dev:amd64     3.13-3
libglobus-callout-doc   3.13-3
libglobus-callout0:amd64        3.13-3
libglobus-common-dbg:amd64      15.26-3
libglobus-common-dev:amd64      15.26-3
libglobus-common-doc    15.26-3
libglobus-common0:amd64 15.26-3
libglobus-ftp-client-dev:amd64  8.13-6
libglobus-ftp-client-doc        8.13-6
libglobus-ftp-client2:amd64     8.13-6
libglobus-ftp-control-dev:amd64 5.12-3
libglobus-ftp-control-doc       5.12-3
libglobus-ftp-control1:amd64    5.12-3
libglobus-gass-copy2:amd64      9.12-3
libglobus-gass-transfer2:amd64  8.8-3
libglobus-gsi-callback-dev:amd64        5.6-3
libglobus-gsi-callback-doc      5.6-3
libglobus-gsi-callback0:amd64   5.6-3
libglobus-gsi-cert-utils-dev:amd64      9.10-3
libglobus-gsi-cert-utils-doc    9.10-3
libglobus-gsi-cert-utils0:amd64 9.10-3
libglobus-gsi-credential-dev:amd64      7.7-3
libglobus-gsi-credential-doc    7.7-3
libglobus-gsi-credential1:amd64 7.7-3
libglobus-gsi-openssl-error-dev:amd64   3.5-3
libglobus-gsi-openssl-error-doc 3.5-3
libglobus-gsi-openssl-error0:amd64      3.5-3
libglobus-gsi-proxy-core-dev:amd64      7.7-3
libglobus-gsi-proxy-core-doc    7.7-3
libglobus-gsi-proxy-core0:amd64 7.7-3
libglobus-gsi-proxy-ssl-dev:amd64       5.7-3
libglobus-gsi-proxy-ssl-doc     5.7-3
libglobus-gsi-proxy-ssl1:amd64  5.7-3
libglobus-gsi-sysconfig-dev:amd64       6.8-3
libglobus-gsi-sysconfig-doc     6.8-3
libglobus-gsi-sysconfig1:amd64  6.8-3
libglobus-gss-assist-dev:amd64  10.12-3
libglobus-gss-assist-doc        10.12-3
libglobus-gss-assist3:amd64     10.12-3
libglobus-gssapi-error-dbg:amd64        5.4-3
libglobus-gssapi-error-dev:amd64        5.4-3
libglobus-gssapi-error-doc      5.4-3
libglobus-gssapi-error2:amd64   5.4-3
libglobus-gssapi-gsi-dbg:amd64  11.13-3
libglobus-gssapi-gsi-dev:amd64  11.13-3
libglobus-gssapi-gsi-doc        11.13-3
libglobus-gssapi-gsi4:amd64     11.13-3
libglobus-io-dev:amd64  11.2-1
libglobus-io-doc
libglobus-io3:amd64     11.2-1
libglobus-libtool
libglobus-libtool-dev
libglobus-libxml2
libglobus-libxml2-dev
libglobus-openssl
libglobus-openssl-dev
libglobus-openssl-module-dev:amd64      4.6-3
libglobus-openssl-module-doc    4.6-3
libglobus-openssl-module0:amd64 4.6-3
libglobus-rls-client-dev
libglobus-rls-client-doc
libglobus-rls-client5
libglobus-rsl-doc
libglobus-xio-dev:amd64 4.15-3
libglobus-xio-doc       4.15-3
libglobus-xio-gsi-driver:amd64  3.6-3
libglobus-xio-gsi-driver-dev:amd64      3.6-3
libglobus-xio-gsi-driver-doc    3.6-3
libglobus-xio-gsi-driver0
libglobus-xio-popen-driver:amd64        3.5-1
libglobus-xio-popen-driver-dev:amd64    3.5-1
libglobus-xio-popen-driver0
libglobus-xio0:amd64    4.15-3
nordugrid-arc-nox-plugins-globus
nordugrid-arc-plugins-globus    4.2.0-2
nordugrid-arc1-plugins-globus
paul@celebrimbor:~/globus-test-case$ 
```

**Comment by bester** [comment]
To use the threaded runtime with Globus, you'll need to set the environment variable GLOBUS_THREAD_MODEL=pthread or call globus_thread_set_model("pthread") as the first globus function you call. Otherwise, a non-threaded event dispatching model (globus_cond_wait polls event lists) is used, which has no thread protection. 

Also, call globus_module_activate(GLOBUS_COMMON_MODULE) in the main thread before calling any globus API functions in any other threads.

**Comment by paulmillar** [comment]
Thanks for the help!

It would be great if this was documented somewhere, or did I miss it?

One final point, you mentioned calling `globus_thread_set_model` "as the first globus function" but also that `globus_module_Activate(GLOBUS_COMMON_MODULE)` is called "before calling any globus API functions".  These seem mutually exclusive statements.

Which would be the correct order?

```
globus_module_activate(GLOBUS_COMMON_MODULE);
globus_thread_set_model("pthread");
```
or
```
globus_thread_set_model("pthread");
globus_module_activate(GLOBUS_COMMON_MODULE);
```

**Comment by bester** [comment]
Sorry, the thread model must be set absolutely first, either in the environment or by calling globus_thread_set_model(

**Comment by paulmillar** [comment]
One more question: does your statement "call globus_module_activate(GLOBUS_COMMON_MODULE) in the main thread before calling any globus API functions in any other threads." mean that the `globus_module_activate` function is (deliberately) not thread safe?

From a casual look at the code, this would seem to be the case, but also should be "fixable".

**Comment by bester** [comment]
In the old pre-pthread-standard days, depending on the which threads implementation Globus was using, it sometimes had to call some initialization function once before anything threaded would remotely work, hence that requirement. It's probably fixable now, but not something we've been bothered by too much.

**Comment by paulmillar** [comment]
Thanks for the explanation.

I've updated the testcase to call `globus_thread_set_model("pthread")` and `globus_module_activate(GLOBUS_COMMON_MODULE)` first, before any subsequent calls to `globus_module_activate`.  With this change, the problem seems to have gone away.

Please fell free to close this ticket.
