### ISSUE TITLE
gsi-openssh-server crashes during package-based upgrade on systemd operating systems

### ISSUE THREAD

**Issue by tpdownes** [globus/globus-toolkit#49]
Significant problem with package upgrades on systemd OSes reported on gsi-openssh-users. I was advised to report it as a GitHub issue.

> I note thing about the upgrade from 5.7-3+gt6 to 7.1p2c-1+gt6 on Debian 8. Did not seem to impact Debian 7 so perhaps systemd-related.
>
>It looks like at some point during the upgrade, the file /var/run/gsisshd.pid disappears. Presumably because the service gets stopped. But, for some reason, the upgrade itself hangs at a point where gsi-openssh-server is in the "iF" state. That is: requested to be installed but failed to install. It looks like it is hanging on "invoke-rc.d gsi-openssh-server start" in gsi-openssh-server.postinst.
>
>FWIW: I think Debian and RHEL are pushing people toward using /run directly rather /var/run, which is now a symlink to /run. But that's a non-issue.
>
>The only solution I can come up with is to reboot and finish the upgrade via apt-get or dpkg --configure. I haven't tried this on servers where I haven't changed /etc/gsissh/sshd_config from your default packaged value so maybe there's an interaction there. Otherwise it happens on every Debian 8 machine I have.

Followed by...

>I can personally confirm that this problem also affects upgrades from 7.1p2c-1+gt6.jessie to 7.1p2e-1+gt6.jessie on Debian 8. My colleagues reports that it also affects the 5.7 to 7.x upgrade on Centos 7.
>
>I think you have a serious problem with in-place upgrades of gsi-openssh-server packages on systemd-based systems. Can you please investigate this and report back?

**Comment by ysvenkat** [comment]
Hi Tom,

Thanks for reporting the issue. I am in the process of reproducing it.

venkat

**Comment by ysvenkat** [comment]
I tried to replicate this on a CentOS 7, but the in-place upgrade worked just fine. I am currently running into issues trying to replicate this on Debian 8.4, as noted here:

https://github.com/globus/globus-toolkit/issues/51

**Comment by drshawnkwang** [comment]
I'm one of Tom's colleagues at UWM and the issue shows up if one tries to upgrade gsi-openssh-server while you have an active ssh session. We have a number of servers (with Debian 8) and they are remotely managed. Thus we ssh into them in order to upgrade the software. The active session causes the upgrade to fail (as Tom detailed above.)

**Comment by tpdownes** [comment]
Was the service actually running?

**Comment by ysvenkat** [comment]
Yes, on CentOS 7 it was running on port 222 (so I had a modified sshd_config) but I didn't have an active ssh session. Will try that. Thanks.

**Comment by ysvenkat** [comment]
I am able to reproduce the problem on a Debian 8.4 VM. It hangs on systemd-tty-ask-password-agent.

pstree:
apt-get upgrade gsi-openssh-server
  ?~T~T?~T~@dpkg --status-fd 20 --configure gsi-openssh-server:amd64
      ?~T~T?~T~@sh /var/lib/dpkg/info/gsi-openssh-server.postinst configure
          ?~T~T?~T~@invoke-rc.d /usr/sbin/invoke-rc.d gsi-openssh-server start
              ?~T~T?~T~@systemctl start gsi-openssh-server.service
                  ?~T~T?~T~@systemd-tty-ask --watch

root@debian84:~# ps -ef | grep apt-get
root     20796 20789  5 17:07 pts/2    00:00:07 apt-get upgrade gsi-openssh-server
root     21661 18327  0 17:09 pts/1    00:00:00 grep apt-get
root@debian84:~# ps -ef | grep 20796
root     20796 20789  5 17:07 pts/2    00:00:08 apt-get upgrade gsi-openssh-server
root     21600 20796  0 17:07 pts/3    00:00:00 /usr/bin/dpkg --status-fd 20 --configure gsi-openssh:amd64 gsi-openssh-server:amd64 gsi-openssh-clients:amd64
root     21663 18327  0 17:10 pts/1    00:00:00 grep 20796
root@debian84:~# ps -ef | grep 21600
root     21600 20796  0 17:07 pts/3    00:00:00 /usr/bin/dpkg --status-fd 20 --configure gsi-openssh:amd64 gsi-openssh-server:amd64 gsi-openssh-clients:amd64
root     21601 21600  0 17:08 pts/3    00:00:00 /bin/sh /var/lib/dpkg/info/gsi-openssh-server.postinst configure
root     21665 18327  0 17:10 pts/1    00:00:00 grep 21600
root@debian84:~# ps -ef | grep 21601
root     21601 21600  0 17:08 pts/3    00:00:00 /bin/sh /var/lib/dpkg/info/gsi-openssh-server.postinst configure
root     21616 21601  0 17:08 pts/3    00:00:00 /bin/sh /usr/sbin/invoke-rc.d gsi-openssh-server start
root     21667 18327  0 17:10 pts/1    00:00:00 grep 21601
root@debian84:~# ps -ef | grep 21616
root     21616 21601  0 17:08 pts/3    00:00:00 /bin/sh /usr/sbin/invoke-rc.d gsi-openssh-server start
root     21646 21616  0 17:08 pts/3    00:00:00 systemctl start gsi-openssh-server.service
root     21670 18327  0 17:10 pts/1    00:00:00 grep 21616
root@debian84:~# ps -ef | grep 21646
root     21646 21616  0 17:08 pts/3    00:00:00 systemctl start gsi-openssh-server.service
root     21647 21646  0 17:08 pts/3    00:00:00 /bin/systemd-tty-ask-password-agent --watch

Investigation continuing.

**Comment by ysvenkat** [comment]
FYI, I do have this in my TODO list and will have another opportunity to work on this in the later part of this month.

**Comment by ysvenkat** [comment]
Hello Tom,

There's a new release 7.1p2f-2 in the Globus stable repo that should fix this issue. Can you try updating to this release via a live gsissh session and verify that it has been fixed?

Thanks,

venkat

**Comment by ysvenkat** [comment]
GSI-OpenSSH release 7.1p2f-2 fixes this issue for Debian; couldn't reproduce on CentOS7 and fix was applicable only to Debian. Please reopen if the issue is encountered again. Thanks.
