### ISSUE TITLE
Doing a PUT and then a GET through the same handle freezes the process

### ISSUE THREAD

**Issue by ayllon** [globus/globus-toolkit#57]
Hello,

I have been debugging an issue where a transfer would block if a file is upload to a GridFTP storage, and then that same file, or any other, is downloaded reusing the same GridFTP client handle.

This only happens, though, when the extension GETPUT is present and used. If RETR and STOR are used instead, everything works as expected.

To reproduce, is enough to use a file like this as a parameter for globus-url-copy

```
file:///tmp/dmc-853.txt gsiftp://ccdcatli156.in2p3.fr:2811//pnfs/in2p3.fr/data/dteam/dmc-853.txt
gsiftp://ccdcatli156.in2p3.fr:2811//pnfs/in2p3.fr/data/dteam/dmc-853.txt file:///tmp/boom.txt
```

This happens

```
# globus-url-copy -vb -f 853.txt
Source: file:///tmp/
Dest:   gsiftp://ccdcatli156.in2p3.fr:2811//pnfs/in2p3.fr/data/dteam/
  dmc-853.txt  ->  dmc-853.txt

Source: gsiftp://ccdcatli156.in2p3.fr:2811//pnfs/in2p3.fr/data/dteam/
Dest:   file:///tmp/
  dmc-853.txt  ->  boom.txt

            0 bytes         0.00 MB/sec avg         0.00 MB/sec inst
```

The download never finishes.

Looking at the exchange between client and server, the file does seem to be transferred

```
gridftp debug :: sending command to gsiftp://ccdcatli164.in2p3.fr:2811//pnfs/in2p3.fr/data/lhcb/user/c/chaen/toto.txt:
GET path=//pnfs/in2p3.fr/data/lhcb/user/c/chaen/toto.txt;pasv;

DEBUG      -> [gridftp_read_stream]
DEBUG       [GridFTP_Request_state::wait_callback] setup gsiftp timeout to 300 seconds
gridftp debug :: response from gsiftp://ccdcatli164.in2p3.fr:2811//pnfs/in2p3.fr/data/lhcb/user/c/chaen/toto.txt:
127 PORT (193,48,99,200,117,180)

gridftp debug :: response from gsiftp://ccdcatli164.in2p3.fr:2811//pnfs/in2p3.fr/data/lhcb/user/c/chaen/toto.txt:
150 Opening BINARY data connection for /pnfs/in2p3.fr/data/lhcb/user/c/chaen/toto.txt

gridftp debug :: reading into data buffer 0x27c6a60, maximum length 4000000
gridftp debug :: response from gsiftp://ccdcatli164.in2p3.fr:2811//pnfs/in2p3.fr/data/lhcb/user/c/chaen/toto.txt:
226 Transfer complete.
```

But it seems the appropriate callback/s are never called, causing the deadlock.

Regards.

**Comment by bester** [comment]
That looks like a firewall issue (either your client is not allowing connections because of NAT or firewall urles, or your server is not allowed to actively connect to that machine's port).

Check out http://toolkit.globus.org/toolkit/docs/6.0/gridftp/admin/index.html#gridftp-config-security-firewalls and see if the server or client configuration information helps.

**Comment by ayllon** [comment]
Hi,

Pretty sure it is not. Download only works.

```
# globus-url-copy -vb -f 853.txt 
Source: gsiftp://ccdcatli156.in2p3.fr:2811//pnfs/in2p3.fr/data/dteam/
Dest:   file:///tmp/
  dmc-853.txt  ->  boom.txt

# cat /tmp/boom.txt 
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
131.169.223.54  lcg-bdii.cern.ch
```

**Comment by bester** [comment]
I'm unable to duplicate this using the Globus GridFTP server. Your endpoint is apparently running the dcache server, so the problem may lie there.

**Comment by msalle** [comment]
@chaen 
you probably need to open a ticket against the [Grid Community Toolkit](https://github.com/gridcf/gct), since the 10.4 is coming from there (EPEL packages are now based on the gct, no longer the globus-toolkit which is EOL).

**Comment by chaen** [comment]
@msalle thanks for the info, will do !
