### ISSUE TITLE
gsisshd prints message about /etc/gsi-openssh to stderr

### ISSUE THREAD

**Issue by tpdownes** [globus/globus-toolkit#62]
My gsisshd configuration doesn't outwardly appear to have any expectation of using files in `/etc/gsi-openssh`. But whenever I run 

`service gsi-openssh-server start`

on Debian 7

or

`/usr/sbin/gsisshd`

on Debian 7 or 8, I get the following message in stderr:

`/etc/gsi-openssh not found.`

prior to gsisshd successfully starting up and finding my configuration in `/etc/gsissh`. It also prints when you attempt to login to a remote server using the client!

```
thomas.downes@remote:~$ gsissh remote-old.ligo.uwm.edu
/etc/gsi-openssh not found.
Last login: Thu Jul 14 13:31:48 2016 from thedude.phys.uwm.edu

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
[remote-old:~] 
```

**Comment by ysvenkat** [comment]
Verfied fix with the unstable version at: http://toolkit.globus.org/ftppub/gt6/unstable/deb/pool/contrib/g/gsi-openssh/gsi-openssh-server_7.1p2f-3+gt6.wheezy_amd64.deb

**Comment by ysvenkat** [comment]
Reopen if issue persists.
