### ISSUE TITLE
Ordered data mode deadlocks

### ISSUE THREAD

**Issue by bbockelm** [globus/globus-toolkit#68]
It seems that ordered data mode deadlocks pretty quickly.

I originally discovered this when using HDFS; however, since HDFS can be tricky to setup, I also reproduced this with the builtin POSIX DSI.

To reproduce, I made a slight change to our shim DSI so I could easily enable/disable this mode:
- Build the OSG extensions DSI, the `ordered_data` branch (https://github.com/opensciencegrid/globus-gridftp-osg-extensions/tree/ordered_mode).  Make and install onto the system (or just put the resulting library into the loader's path).
- Add the following to the `gridftp.conf`:
  
  ```
  load_dsi_module osg
  $OSG_REQUIRES_ORDERED_DATA 1
  ```
- Test the following:
  
  ```
  globus-url-copy -p 10 -vb file:////dev/zero gsiftp://hostname.example.com//dev/null`
  ```

When `OSG_REQUIRES_ORDERED_DATA` is set, the ordered data mode flag is added to the DSI.  I found that `globus-url-copy` deadlocks fairly quickly with the flag set and works without the flag.

(reproduction instructions are about the same with the HDFS DSI, but this one is easier to setup - less system dependencies).

@michaellink @stumartin

**Comment by michaellink** [comment]
Fixed in globus-ftp-control-7.7.
