### ISSUE TITLE
Slow grid-mapfile-add-entry

### ISSUE THREAD

**Issue by thiell** [globus/globus-toolkit#69]
I am using globus-gss-assist-progs-10.15-1.el6+gt6.x86_64

The grid-mapfile-add-entry is very slow and doesn't seem to scale well. Sometimes up to 1 minute to add an single entry. I administrate a new XSEDE resource with about 1200 DNs only for now, but I am worried as it is quickly growing. Sometimes we receive 10's of users with each 5-10 DNs to add in batch and this takes too long... Is there a more efficient way to add grid-mapfile entries?

Thanks!

**Comment by bester** [comment]
That script is pretty lowest-common-denominator /bin/sh which does some line-by-line processing, so it's bound to be slow.

That said, if you:

1. Are the only person changing the gridmap file
2. Are only adding users with new DNs
3. Only have one LN per DN

You could do something like

cp /etc/grid-security/grid-mapfile gridmap.new
echo "$dn $ln" >> gridmap.new
...
grid-mapfile-check-consistency -f gridmap.new
if [ $? = 0 ]; then
  cp gridmap.new /etc/grid-security/grid-mapfile 
fi

If it's a big problem, we can probably rewrite it in something else.

**Comment by thiell** [comment]
Hi @bester and thank you for your quick reply.

1) yes, the gridmap file is changed from a single server, originally called using cron
2) no, sometimes we add duplicate DNs, so the script should still check that
3) we do have one LN per DN as we made sure the LN is unique on the cluster

I didn't know about grid-mapfile-check-consistency, I will take a look at it, thanks!

Using grid-mapfile-add-entry is a growing problem indeed as we have to process projects and associated accounts that comes from the central XSEDE database in a timely manner. As an example, yesterday a single project with 40 users took more than half an hour to be processed due to grid-mapfile-add-entry slowness. I think the bigger problem of this script is not that it's a shell script but more the way it is written. It does a `while read line` on each line, processes the delimiters, and then copies all lines to a temporary files. Using commands like grep and sed could probably drastically reduce the processing time.

**Comment by bester** [comment]
I rewrote the logic in perl to reduce the process and I/O overhead: [grid-mapfile-add-entry](https://gist.github.com/bester/9556547756449179a6c7f8ab70c1043e). Can you give that one a try?

If that's still not usable, I'd probably want to use a different approach:  read and validate new entries from a file and then write the gridmap once at the end.

**Comment by thiell** [comment]
Hi @bester,

I just tested with a gridmap file having 1169 entries, and it takes 10s with the old one vs 0.06s with your new script! That's 166 times faster! We're good now. Thank you for looking at this so quickly!

**Comment by jpnavarro** [comment]
Hi Joe,

When will this improvement make it to Globus stable?

**Comment by bester** [comment]
That version is available in stable now (globus-gss-assist-progs >= 10.18).
