### ISSUE TITLE
myproxy store command requires all the pieces to be in one send()

### ISSUE THREAD

**Issue by DrDaveD** [globus/globus-toolkit#73]
I have noticed that with the myproxy store command from my python client (cigetcert) that I cannot send the 3 pieces of a proxy chain (proxy cert, proxy key, original cert) as 3 separate socket send() commands, because if I do I get an error back from MyProxy "Credentials are not valid."  I have to have them all together in one send().  Brian Bockelman suggested that is a bug making the protocol unreliable because the network can also sometimes split up packets.  Do you agree?

**Comment by DrDaveD** [comment]
I forgot to mention that this is myproxy-server-6.1.15-2.osg33.el6

**Comment by jbasney** [comment]
See comments in the MyProxy `GSI_SOCKET_read_token()` and `GSI_SOCKET_credentials_accept_ext()` functions. MyProxy has always been fragile to TLS record fragmentation. Clients should try to send requests in a single TLS record. Fragmentation at the TCP/IP network layer should not be an issue, however.

We thought about fixing it back in 2003 but didn't see a way to fix it without a re-write of MyProxy's GSI_SOCKET abstraction and/or breaking backward compatibility in the MyProxy protocol.

**Comment by DrDaveD** [comment]
Ok, thanks for the explanation.
