### ISSUE TITLE
Slow grid-mapfile-delete-entry

### ISSUE THREAD

**Issue by thiell** [globus/globus-toolkit#84]
Hi, we now have the same performance problem with `grid-mapfile-delete-entry`. We use XSEDE AMIE and for some projects, we receive hundreds of modifications. The script takes 22+ seconds to delete a single entry, leading to hours of processing for the whole AMIE process for just a few XSEDE project adjustments. Some users have 10+ DNs so the gridmap file is big. Performance improvement in the same way than `grid-mapfile-add-entry` (#69) would be very welcomed. :)

**Comment by bester** [comment]
Can you give this one a try:

[grid-mapfile-delete-entry](https://gist.github.com/bester/a0f5f2d141fe4f3f9271a5c141351393)

**Comment by bester** [comment]
Have you had a chance to confirm this works for you?

**Comment by thiell** [comment]
@bester: Sorry for the delay, this new script works for us and does fix our execution time issue. Thanks much!

**Comment by bester** [comment]
The new code is available in globus-gss-assist-progs 10.21
