### ISSUE TITLE
Myproxy test suite errors with openssl 1.1.0

### ISSUE THREAD

**Issue by ellert** [globus/globus-toolkit#88]
With the latest changes from git, the myproxy test suite almost works when compiling using OpenSSL 1.1.0, except for two of the tests:

MyProxy Test 3T (retrieve stored credential w/ trustroots): FAILED
MyProxy Test 41 (retrieve trustroots w/o authentication): FAILED
MyProxy Tests Complete: 54 tests passed, 2 tests failed

The failures are due to a segmentation fault within the call to BIO_ssl_shutdown() in the myproxy_bootstrap_trust function in myproxy.c:
https://github.com/globus/globus-toolkit/blob/globus_6_branch/myproxy/source/myproxy.c#L638

If I comment out that call the test suite completes without errors, but I don't think that is the correct fix. Does anyone have a better way?

**Comment by bester** [comment]
It looks like is an bug in openssl 1.1.0. I've [reported it](https://github.com/openssl/openssl/issues/2199).

However, removing the BIO_ssl_shutdown() looks to be an ok solution, as BIO_free() invokes the equivalent functionality without the error.

**Comment by bester** [comment]
Fixed in myproxy RPM version 6.1.25
