### ISSUE TITLE
MICv2 doesn't work when a peer is running on CentOS 6

### ISSUE THREAD

**Issue by ysvenkat** [globus/globus-toolkit#92]
When one of the Globus GSI peers is running on CentOS6 and the other on a non-CentOS6 machine, SSL_export_keying_material() exports key material that doesn't agree with the peer's exported key material. This results in the new MICv2 MIC verification failures. This issue impacts GSI-OpenSSH. Specifically, it causes connections to fail when one of the peers is using OpenSSL 1.1 and the other peer is running on CentOS6. The following bug report has been filed with CentOS6.8:

https://bugs.centos.org/view.php?id=12959

**Comment by jbasney** [comment]
Comparing the changelogs between openssl-1.0.1e-48.el6_8.4.x86_64 and openssl-1.0.1e-60.el7_3.1.x86_64 I see:

> Thu Apr 07 2016 Tomáš Mráz <tmraz@redhat.com> 1.0.1e-56
> use correct digest when exporting keying material in TLS1.2 (#[1289620](https://bugzilla.redhat.com/show_bug.cgi?id=1289620))

Might it explain this problem?

**Comment by ysvenkat** [comment]
That's the issue. Thanks for finding it. I have rebuilt the OpenSSL 1.0.1e RPM on CentOS6.8 with the one line patch noted in that bug report, applied and the patch fixes the issue. I have updated the bug report filed with CentOS that's referred to in the main post above, with a request to backport the fix to CentOS6.8.

**Comment by ysvenkat** [comment]
Per Jim Basney's suggestion, I have tried setting GSS_C_CONF_FLAG in the gsissh client and that causes AES256-GCM-SHA384 to be chosen instead of NULL-SHA256 and the exported key materials match and the connection succeeds. I will make another release of GSI-OpenSSH with the GSS_C_CONF_FLAG  flag set. Thanks for the suggestion, Jim!

**Comment by ysvenkat** [comment]
I thought I had tested that setting GSS_C_CONF_FLAG would work with older GSISSH server versions, but I find it doesn't work with xstream.stanford.xsede.org for example, which runs OpenSSH_6.4p1-hpn14v1 GSI_GSSAPI_GPT_5.7 GSI. The server closes the connection after init_sec_context succeeds on the client end:

------------------
globus_i_gsi_gss_get_token exiting: major_status=0
init_sec_context:major_status:00000000:gss_state:4 req_flags=00000033:ret_flags=000000ff
gss_init_sec_context exiting: major_status=0
gss_release_buffer entering
gss_release_buffer exiting: major_status=0
debug3: Wrote 960 bytes for a total of 5349
Connection closed by 171.66.97.72
------------------

So, it looks like turning GSS_C_CONF_FLAG on subject to the user setting GSISSH_FORCE_CONF_FLAG in the environment is the way to go.

**Comment by ysvenkat** [comment]
This issue is fixed in CentOS 6.9, but if one of the peer is running on CentoS 6.8 or earlier, the client can set GSISSH_FORCE_CONF_FLAG in the environment which is supported in the below release:
https://github.com/globus/gsi-openssh/releases/tag/7.3p1b
