### ISSUE TITLE
Missing source tarballs

### ISSUE THREAD

**Issue by ellert** [globus/globus-toolkit#99]
There has been a set of updates to the globus toolkit packages at
http://toolkit.globus.org/ftppub/gt6/stable/rpm/
where the corresponding source tarballs have not been published in
http://toolkit.globus.org/ftppub/gt6/packages/

Could you look into putting the missing files on the server?

The list of missing source tarballs includes:

globus_ftp_client-8.35.tar.gz
globus_gass_cache_program-6.7.tar.gz
globus_gass_copy-9.24.tar.gz
globus_gass_copy-9.27.tar.gz
globus_gssapi_gsi-12.14.tar.gz
globus_net_manager-0.17.tar.gz
globus_xio-5.15.tar.gz
globus_xio_pipe_driver-3.10.tar.gz
myproxy-6.1.26.tar.gz

**Comment by bester** [comment]
The latest source packages should be available now.
